name: Test on Windows and macOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'  # Specify your Ruby version

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Run tests
      run: bundle exec rake
